type EstForecast = {
  id?: number;
  key?: string;
  symbol: string;
  company: string;
  industry: string;
  callTime: string;
  beta: number | null;
  marketCapEstForecast: string;
  epsEstimateESTEarnings: number | null;
  ytdPerformance: number | null;
  aiRating: number | null;
  yahooRec: string;
  priceTarget: number | null;
  grok: string;
  gpt: string;
  forecast: string;
  earningsDate: string;
  revenueForecast: number | null;
  revenueForecastPoint: number | null;
  netMargin: number | null;
  netMarginPoint: number | null;
  epsTrend: number | null;
  epsTrendPoint: number | null;
  avgSurpriseMagnitude: number | null;
  avgSurpriseMagnitudePoint: number | null;
  epsBeatFreq: number | null;
  epsBeatFreqPoint: number | null;
  revenueBeatFreq: number | null;
  revenueBeatFreqPoint: number | null;
  postEarningDrift: number | null;
  postEarningDriftPoint: number | null;
  grokRatingPoint: number | null;
  gptRating: number | null;
  gptRatingPoint: number | null;
  lsegNewsScore1d: number | null;
  lsegNewsScore1dPoint: number | null;
  lsegNewsTotalScorePoint: number | null;
  lsegNewsScore3d: number | null;
  lsegNewsScore3dPoint: number | null;
  article12h: number | null;
  article12hPoint: number | null;
  marketpsychEarningsDirectionZ: number | null;
  marketpsychEarningsDirectionZPoint: number | null;
  marketpsychEarningsForecastZ: number | null;
  marketpsychEarningsForecastZPoint: number | null;
  marketpsychRevenueDirectionZ: number | null;
  marketpsychRevenueForecastZ: number | null;
  marketpsychPriceUpZ: number | null;
  marketpsychOptimismZ: number | null;
  marketpsychTrustZ: number | null;
  aggregateScore: number | null;
  aggregateScorePoint: number | null;
  noteForTrader: string;
  forecastPct: number | null;
  entryDate: string;
  entryPrice: number | null;
  highestPrice: number | null;
  highest3DaysPrice: number | null;
  lowest3DaysPrice: number | null;
  currentPrice: number | null;
};

type EstForecastFilterItem = {
  id: number;
  key?: string;
  symbol: string;
  company: string;
  industry: string;
  callTime: string;
  beta: number | null;
  marketCapEstForecast: string;
  marketCap: string;
  forecast: string;
  epsEstimateESTEarnings: number | null;
  epsEstimatePoint: number | null;
  prevEstimate: string;
  revenueForecast: number | null;
  revenueForecastPoint: number | null;
  netMargin: number | null;
  netMarginPoint: number | null;
  epsTrend: number | null;
  epsTrendPoint: number | null;
  avgSurpriseMagnitude: number | null;
  avgSurpriseMagnitudePoint: number | null;
  epsBeatFreq: number | null;
  epsBeatFreqPoint: number | null;
  revenueBeatFreq: number | null;
  revenueBeatFreqPoint: number | null;
  postEarningDrift: number | null;
  postEarningDriftPoint: number | null;
  ytdPerformance: number | null;
  ytdPerformancePoint: number | null;
  aiRating: number | null;
  aiRatingPoint: number | null;
  aggregateScore: number | null;
  aggregateScorePoint: number | null;
  routerRec: string;
  yahooRec: string;
  yahooRecPoint: number | null;
  priceTarget: number | null;
  priceTargetPoint: number | null;
  grok: string;
  grokPoint: number | null;
  gpt: string;
  gptPoint: number | null;
  gptRating: number | null;
  gptRatingPoint: number | null;
  lsegNewsScore1d: number | null;
  lsegNewsScore1dPoint: number | null;
  lsegNewsScore3d: number | null;
  lsegNewsScore3dPoint: number | null;
  article12h: number | null;
  article12hPoint: number | null;
  marketpsychEarningsDirectionZ: number | null;
  marketpsychEarningsDirectionZPoint: number | null;
  marketpsychEarningsForecastZ: number | null;
  marketpsychEarningsForecastZPoint: number | null;
  marketpsychRevenueDirectionZ: number | null;
  marketpsychRevenueDirectionZPoint: number | null;
  marketpsychRevenueForecastZ: number | null;
  marketpsychRevenueForecastZPoint: number | null;
  marketpsychPriceUpZ: number | null;
  marketpsychPriceUpZPoint: number | null;
  marketpsychOptimismZ: number | null;
  marketpsychOptimismZPoint: number | null;
  marketpsychTrustZ: number | null;
  marketpsychTrustZPoint: number | null;
  tradeDate: string;
  forecastPct: number | null;
  entryDate: string;
  entryPrice: number | null;
  highestPrice: number | null;
  highest3DaysPrice: number | null;
  lowest3DaysPrice: number | null;
  currentPrice: number | null;
};

type CountByDate = {
  date: string;
  total: number;
};
