type ListHighActivityFilter = Filter & {
  fromDate?: string;
  toDate?: string;
  fromVolume?: number;
  toVolume?: number;
  fromAtr?: number;
  toAtr?: number;
  drop1_5Pct?: string;
  underWillrMinus80?: string;
  underSma50?: string;
  underSma200?: string;
  drop3Pct?: string;
  drop5Pct?: string;
  drop3Pct2Prev?: string;
  drop5Pct2Prev?: string;
  drop10Pct2Prev?: string;
  criticalNews?: string;
  nextEarning?: string;
  fromBeta?: number;
  toBeta?: number;
};

type ListHighActivity = {
  key: string;
  symbol: string;
  datetime: string;
  timeframe: string;
  avgVolume: number;
  atr: number;
  beta: number;
  marketCapHighActivity: string;
  underWillrMinus80: boolean;
  underSma50: boolean;
  underSma200: boolean;
  dropPctSma200: number;
  dropPct2prevSma200: number;
  dropPct: number;
  drop1_5Pct: boolean;
  drop3Pct: boolean;
  drop5Pct: boolean;
  dropPct2prev: number;
  drop3Pct2prev: boolean;
  drop5Pct2prev: boolean;
  drop10Pct2prev: boolean;
  criticalNews?: string;
  nextEarning?: string;
  earningsScore: number;
  epsEstimate: number;
  sentimentScore: number;
  fundamentalScore: number;
};
