type Watchlist50DaysFilter = Filter & {
  period?: string;
  fromMarketCap?: number;
  toMarketCap?: number;
  industry?: string;
  sector?: string;
};

type WatchlistIn50Days = {
  key: string;
  symbol: string;
  companyName: string;
  period: string;
  AIRating: number;
  AIRecommendation: string;
  AIExplain: string;
  previousClose: number;
  previousPrice: number;
  currentPriceWatchlist: number;
  lowest50: number;
  changeLowest50Realtime: number;
  changeLowest50: number;
  highest50: number;
  lowest20: number;
  changeLowest20: number;
  changeLowest20Realtime: number;
  lowest10: number;
  changeLowest10: number;
  changeLowest10Realtime: number;
  highest20: number;
  highest10: number;
  average: number;
  median: number;
  sma50: number;
  sma20: number;
  yahooPriceTargetMean: number;
  yahooPriceTargetHigh: number;
  yahooPriceTargetLow: number;
  buy: number;
  strongBuy: number;
  sell: number;
  strongSell: number;
  hold: number;
  marketCapWatchList: number;
  sector: string;
  industry: string;
  subindustry: string;
  createdAt: string;
};
